### ISSUE TITLE
If you use any port other than the 80 port (web), it does not work Nodered 

### ISSUE THREAD

**Issue by Jnas** [open-rpa/openflow#38]
Hello.
Tried to use the following settings:
```

web:
    restart: always
    image: "cloudhack/openflow:0.0.550"
    environment:
      .............
      - protocol=http
      - port=88
      - domain=localhost.openrpa.dk
       ......
      - saml_issuer=uri:localhost.openrpa.dk
      ....
      - NODE_ENV=development
      - api_ws_url=ws://localhost.openrpa.dk
nodered:
    restart: always
    image: "cloudhack/openflownodered:0.0.550"
    environment:
      - nodered_sa=nodered1
      - queue_prefix=

      - saml_federation_metadata=http://web:88/issue/FederationMetadata/2007-06/FederationMetadata.xml
      - saml_issuer=uri:localhost.openrpa.dk:88
      - saml_entrypoint=http://localhost.openrpa.dk:88/issue
      - saml_baseurl=http://localhost.openrpa.dk:1880/
      - port=1880
     .....
```

In Docker, I see that everything starts and works, but Nodered does not open as if it is not running.
I suspect that the cause may be _saml_federation_metadata_, but tried different options and did not work.
What reason could it be ?
